### ISSUE TITLE
Bind grn_obj_flush()

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#100]
* https://github.com/groonga/groonga/blob/v5.0.5/include/groonga/groonga.h#L910
* https://github.com/groonga/groonga/blob/v5.0.5/lib/db.c#L9737-L9763

**Comment by myokoym** [comment]
I'm considering about an API.

Ideas:

* Groonga::IO.flush
* Groonga::Object#flush

References:

* http://groonga.org/docs/reference/commands/io_flush.html
* http://ruby-doc.org/core-2.2.2/IO.html#method-i-flush

**Comment by kou** [comment]
Define `Groonga::Flushable` module, define `Groonga::Flushable#flush` and include the module from `Groonga::Table`, `Groonga::Column` and `Groonga::Database`.

**Comment by myokoym** [comment]
Thanks! I agree with this plan.

**Comment by myokoym** [comment]
Done by the commits https://github.com/ranguba/rroonga/compare/9459825...2102762
