### ISSUE TITLE
Reply to the email of ruby-talk

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#127]
>
This looks awesome - how does it compare with Xapian?
>
http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/435148

**Comment by myokoym** [comment]
The Xapian Project
http://xapian.org/

**Comment by cosmo0920** [comment]
Xapian project has less CJK-ready tokenizer implementations than Groonga.
There is only cjk-tokenizer in Xapian project: https://xapian.org/docs/sourcedoc/html/cjk-tokenizer_8cc.html.
It is the one of the advantages of Groonga and related project.
But, Xapian project has a bunch of its language bindings.
It is the one of the disadvantages of Groonga and related project.

Any thoughts?

**Comment by myokoym** [comment]
Thanks for the comment! I used it as a reference.
