### ISSUE TITLE
Groonga::Record#columns does not seem work

### ISSUE THREAD

**Issue by hamadu** [ranguba/rroonga#136]
Groonga::Record#columns から正しいデータが取れないようです。以下再現コードで、テーブルのカラムの配列 `[number, name]` が返ってきてほしいのですが、実行すると空配列 `[]` が返ってきます。
(Groonga::Record#columns does not seem work. In reproducing code below, expected return value is `[number, name]`, but actual value was `[]`.)

```rb
# reproducing code
require 'groonga'

# create database and table if not exist
begin
  Groonga::Database.create(path: "./data/test.db")
  Groonga::Schema.create_table('SomeTable', type: :hash, key_type: 'UInt32')
  Groonga::Schema.change_table('SomeTable') do |table|
    table.uint32('number')
    table.text('name')
  end
rescue => _
  Groonga::Database.open('./data/test.db')
end

@purchases = Groonga['SomeTable']

# put some data if not exist
unless @purchases.exist?(1)
  1.upto(10).each do |id|
    @purchases.add(id, { number: id, name: 'a' * id })
  end
end

# fetch row and confirm columns
results = @purchases.select do |record|
  record[:number] == 7
end

results.each do |record|
  puts "class: #{record.class}"      # => class: Groonga::Record
  puts "columns: #{record.columns}"  # => columns: []
end
```

### 環境(Environments)

OSX 10.11.5(El Capitan)
Groonga 6.0.9 [darwin15.6.0,x86_64,utf8,match-escalation-threshold=0,nfkc,msgpack,mruby,onigmo,zlib,kqueue]
ruby 2.2.3p173
rroonga 6.0.9

**Comment by kou** [comment]
このケースで`[number, name]`が欲しいときは次のようにしてください。

```ruby
p record.key.columns.collect(&:local_name) # => ["name", "number"]
```

`Groonga::Table#select`は「検索対象のテーブル（今回だと`@purchases`）」ではなく、「検索対象のテーブルを参照しているテーブル」を返します。`Groonga::Record#columns`は自身が所属するテーブルのカラムを返します。今回の場合だと`results`の中の`record`は「検索対象のテーブルを参照しているテーブル」に所属しているのでこのテーブルのカラムを返します。しかし、このテーブルはなにもカラムを持っていないので空の配列を返します。

では、どうして`record.columns`だと空の配列で`record.key.columns`だと`[name, number]`が返ってくるかということについて説明します。

「検索対象のテーブルを参照しているテーブル」は`Groonga::Hash`テーブルです。この種類のテーブルはキーを持ちます。Groongaではキーは型を持っています。Groongaでの型とは「値の取りうる範囲」のことです。`UInt32`は「`0...2**32`」ですし、`ShortText`は「0バイト以上4096バイト以下の文字列」です。型にはテーブルを指定することもできます。この場合はそのテーブルのレコード（ID）が「値の取りうる範囲」になります。そして、型としてテーブルを指定した場合、他のテーブルを参照していることになります。

今回の場合は`results`のキーの型が`@purchases`になっています。キーの型は`Groonga::Table#domain`（型は「値の取りうる範囲」のことで「値の取りうる範囲」とは数学で言う「定義域」なのでdomainになっています）で取得できます。

```ruby
p results.domain # => #<Groonga::Hash id: <256>, name: <SomeTable>, ...>
p @purchases     # => #<Groonga::Hash id: <256>, name: <SomeTable>, ...>
```

`results`のキーの型が`@purchases`なので`record.key`は`@purchases`のレコードです。

```ruby
p record.key.table # => #<Groonga::Hash id: <256>, name: <SomeTable>, ...>
```

そのため、`record.key.columns`とすると`@purchases`のカラムが返ってきます。

一方、`record.table`は`results`です。

```ruby
p record.table # => #<Groonga::Hash id: <2147483649>, name: (anonymous), ...>
p results      # => #<Groonga::Hash id: <2147483649>, name: (anonymous), ...>
```

`results`はキーで検索対象のテーブルを参照しているだけでカラムは定義していないので`record.columns`は空の配列を返します。

```ruby
p record.columns # => []
```

**Comment by hamadu** [comment]
とても良くわかりました！ありがとうございます。

**Comment by kou** [comment]
よかったです！
同じことで困っている人がいたら助けてあげてもらえると助かります！
