### ISSUE TITLE
Release 6.1.0

### ISSUE THREAD

**Issue by kenhys** [ranguba/rroonga#137]
See [doc/text/release.md](https://github.com/ranguba/rroonga/blob/master/doc/text/release.md).
- [x] 0. Support Groonga 6.1.0
- [x] 1. Add release entry (English) to [doc/text/news.md](https://github.com/ranguba/rroonga/blob/master/doc/text/news.md).
- [x] 2. Translate news to Japanese.
- [x] 3. Upload to [RubyGems.org](https://rubygems.org/gems/rroonga).
  - [x] Upload normal gem (`rake release`).
  - [x] Upload Windows gem (See also [doc/text/cross-compile.md](https://github.com/ranguba/rroonga/blob/master/doc/text/cross-compile.md)).
- [x] 4. Update [ranguba.org](https://github.com/ranguba/ranguba.org).
  - [x] Update the latest version and release date.
  - [x] Update reference manual (`rake release:references:upload`).
- [ ] 5. Announce on mailing lists.
  - [ ] groonga-dev (Japanese)
    - example: https://osdn.jp/projects/groonga/lists/archive/dev/2016-March/003975.html
  - [ ] groonga-talk (English)
    - example: https://sourceforge.net/p/groonga/mailman/message/34931231/
  - [ ] ruby-list (Japanese) (optional)
    - example: http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-list/50285
  - [ ] ruby-talk (English) (optional)
    - example: http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/435147

**Comment by kenhys** [comment]
6.0.9から6.1.0への追従に関して追加の公開APIはない。

**Comment by kenhys** [comment]
ただ、カラムインデックスのフラグについては未サポートになっている。
これに対応して6.1.0としよう。

**Comment by kenhys** [comment]
https://github.com/ranguba/rroonga/pull/138 対応してみたPR.
ただしRroonga的にはちょっとお行儀がよろしくなかったので修正する。

**Comment by kenhys** [comment]
一旦作業を保留。このあとどうすすめるかは @myokoymさんと相談する。

**Comment by kenhys** [comment]
#138 がマージされたのでこれでリリースしよう。

**Comment by kenhys** [comment]
gemをアップロードするところまで済。

**Comment by kenhys** [comment]
ranguba.orgも更新した。

**Comment by kenhys** [comment]
あとはリリースアナウンス。

**Comment by myokoym** [comment]
6.1.3が出たので閉じます。
