### ISSUE TITLE
Some questions about indexing and querying

### ISSUE THREAD

**Issue by tomas** [ranguba/rroonga#148]
Hello, 

I discovered Groonga/Rroonga recently and it looks great. Unfortunately the documentation in english is scarce so I'm not sure I'm doing things correctly. I hope you guys can help me.

a) Is there a way to do an inverse reference from one table to another? For example, given the following schema:

    schema.create_table("Bookmarks") do |table|
      table.text("title")
    end

    schema.create_table("Comments") do |table|
      table.reference("bookmark")
      table.text("content")
    end

What's the most optimal way of getting all comments that are linked to a Bookmark? I'm assuming I could do:

    comments.select { |c| c.bookmark == bookmark }

But I'm not sure if this is the best/fastest way.

b) Is indexing needed or recommended whenever you want to filter by a specific column, or only required for full text search? (i.e. in the above example, would it help to define an index column on `Comments.bookmarks`?)

c) Is there a speed or memory penalty in selecting records using a block, in comparison with using a query/expression?

d) How I do perform a completion/correction/suggestion query? What table types it is supported on?

e) Is there a way to perform a similarity query on multiple columns? So far I've only found a way to perform that type of query but on a single (indexed) column. I'm not sure if there are other ways around this.

Thanks in advance for the help and sorry for the long list of questions!

**Comment by komainu8** [comment]
Thank you for your questions.

(a)'s schema is correct.
We will research that the query of (a) is better or not.

We will also research questions of (b) - (e).
Therefore we appreciate your patience as it might take some time.

**Comment by tomas** [comment]
Sure, no problem. Thanks again for the help!

**Comment by tomas** [comment]
Hi, any news?

I'm not really asking for a scientific measurement, just a general notion to see whether I'm doing things the right way or not. :)

**Comment by komainu8** [comment]
Ah... sorry. I don't have had time for confirming your questions in the last week.
Could you give me some more time?

**Comment by kenhys** [comment]
a) In above example, it seems that the following way is simple.

```ruby
records = comments.select do |record|
  record.bookmark._id > 0
end
records.each do |record|
  p record.content
end
```

b) in generally speaking, indexing is recommended. because if there is no indexes, sequential search will be executed instead. In the above example, `Bookmarks.title` and `Comments.content` is the recommened to create index columns. `Comments.bookmark` is reference column, so no need to create index for it.

**Comment by tomas** [comment]
Thanks for the answers! 

a) Looking at your code, it seems that the upper block is returning all comments, am I right? I want to know what's the best way of getting all comments _that are linked to a Bookmark_. What does `bookmark._id > 0` do?

b) I see. But creating an index on `Bookmarks.title` or `Comments.content` wouldn't really help in filtering comments that are linked to a bookmark (not doing a fulltext query).

I have a new question, by the way!

f) What's the best way of updating multiple records? I'm looking for the equivalente of the SQL query `update comments set content = 'foo' where id > 10`.

**Comment by kenhys** [comment]
a) Yes.
`record.bookmark._id > 0` means that comment record is linked to bookmark (it is equivalent to "select Bookmarks where _id > 0").
If comment record is not linked to bookmark, `bookmark._id > 0` is not satisfied because `bookmark._id` will be 0), as a result, all comments which is linked to bookmark is returned.
(Maybe Groonga dump data will help to understand it. - groonga PATH_TO_DB dump)

b) I thought you want to filter based on text contents, so if you just want to filter comments which is linked to bookmarks, there is no need to create index columns.

f) I don't know the best way, but the following way is what you want.

```
records = comments.select do |record|
  record["_id"] > 10
end
records.each do |record|
  record.content = "updated comment"
end
```

**Comment by kenhys** [comment]
d) As far as I know, Rroonga doesn't support completion/correction/suggestion in Ruby friendly way.

To do it, it need to prepare specific schema & data.

* Step 1: create dataset table
* Step 2: load completion/correction/suggestion data
* Step 3: execute suggest query

Step1: create specific tables

```
% groonga-suggest-create-dataset PATH_TO_DB query
```
It creates some tables for `query` dataset( you can use other dataset name. this is just example). These table must be created by specific naming rules.

Step2: load data

If you want to do completion,  load http://groonga.org/docs/reference/suggest/completion.html#how-it-learns data.

```
load --table event_query --each 'suggest_preparer(_id, type, item, sequence, time, pair_query)'
[
{"sequence": "1", "time": 1312950803.86057, "item": "e"},
{"sequence": "1", "time": 1312950803.96857, "item": "en"},
{"sequence": "1", "time": 1312950804.26057, "item": "eng"},
{"sequence": "1", "time": 1312950804.56057, "item": "engi"},
{"sequence": "1", "time": 1312950804.76057, "item": "engin"},
{"sequence": "1", "time": 1312950805.86057, "item": "engine", "type": "submit"}
]
```

It learns sequential input with timestamps. `engine` is recognized finally committed word.
It is easy to use groonga to load above load data. (save above text to load.grn)

```
% groonga --file load.grn PATH_TO_DB
```

Step3 execute completion query

```
# completion
context = Groonga::Context::default
command = "suggest --table item_query --column kana --types complete --frequency_threshold 1 --query en"
context.send(command)
_, result = context.receive
p JSON.parse(result)
```

It returns `engine` as completion of `en`.

```
{"complete"=>[[1], [["_key", "ShortText"], ["_score", "Int32"]], ["engine", 1]]}
```

You can execute correction and suggestion in similar way. (load learning data and execute `--types correction ` or `--types suggest` )

http://groonga.org/docs/reference/suggest/correction.html
http://groonga.org/docs/reference/suggest/suggestion.html

**Comment by tomas** [comment]
Thank you @kenhys!

So from what I see, both selecting or updating multiple records rely on passing a block for filtering them. However, I see that `table.select` can also be called using a query instead of a block. Would that be less or more performant than using block notation? (Question c)

**Comment by kenhys** [comment]
> e) Is there a way to perform a similarity query on multiple columns? So far I've only found a way to perform that type of query but on a single (indexed) column. I'm not sure if there are other ways around this.

It seems that similar search works for a single column, so  `context.send("RAW_GROONGA_SIMILAR SEARCH_COMMAND...")` is  a workaround for it.

**Comment by kenhys** [comment]
c) You mean difference between `table.select do |record| ... end` and `table.select("column @ \"xxx\")` style?

**Comment by tomas** [comment]
Yes indeed!

**Comment by kenhys** [comment]
In point view of performance, `table.select do |record| ... end` and `table.select("column @ \"xxx\")` style are  same.
