### ISSUE TITLE
Index/fulltext search using query vs block

### ISSUE THREAD

**Issue by tomas** [ranguba/rroonga#195]
Hello,

I have a index table/column created and trying to perform a fulltext search using the `@` operator, like this:

    table.select "description:@some\\ thing"

But apparently it only finds records whose description includes the "some thing" text in that exact order, and not records that contain "thing some" (reverse order). 

What I'd like is to perform a fulltext search and get the records with the words in both directions-- the same result I get when doing:

    table.select { |rec| rec['description'].match("some thing") }

The reason I want to use the query method is because I want to combine the fulltext search with other conditions.

So my question is: is this happening because the first method does not use the index column and instead run a "normal" (non-fulltext) search? I tried passing the `match_column` parameter but I couldn't make it work.

Strangely, when calling `#search` on the index column directly (`index.search("some thing")`) I also get the same results as the first scenario and not the second one. Why does this happen?

Hope you can help me out and thanks in advance!

**Comment by kou** [comment]
`table.select "description:@some\\ thing"` finds `some thing`.

You can use `table.select "description:@some description:@thing"` that finds `some` AND `thing`.

**Comment by tomas** [comment]
Thank you @kou 

How can I know or make sure that the query is actually using the index column?

**Comment by kou** [comment]
You can confirm it by debug log message.

Here is a code to enable debug log:

```ruby
Groonga::Logger.path = "/tmp/groonga.log"
Groonga::Logger.max_level = :debug
```

**Comment by tomas** [comment]
Great. Would you mind explaining the difference between doing `index.search` and calling `#match` using the block strategy?

**Comment by kou** [comment]
`index.search` searches the give term (`some thing`) as is.
`#match` parses the given query (`some thing` -> `some` AND `thing`) and executed the parsed query.
https://groonga.org/docs/reference/grn_expr/query_syntax.html is the syntax for query.

**Comment by tomas** [comment]
I see. Thank you!
