### ISSUE TITLE
the config.guess in groonga-latest.tar.gz is too old,and it cannot guess build type

### ISSUE THREAD

**Issue by zangruochen** [ranguba/rroonga#220]
Architecture: loongarch64

LoongArch is a new architecture that is already supported by linux-6.1, gcc-12.

My build type is loongarch64-unknown-linux-gnu,and the config.guess in groonga-latest.tar.gz is too old,it cannot guess build type.

**Comment by kou** [comment]
How did you install Rroonga?

**Comment by kou** [comment]
Did you check https://packages.groonga.org/source/groonga/groonga-latest.tar.gz ?

**Comment by kou** [comment]
Does GNU Autotools support loongarch64?

**Comment by kou** [comment]
BTW, we will use CMake based build instead of GNU Autotools based build eventually here: https://github.com/ranguba/rroonga/blob/master/ext/groonga/extconf.rb#L197

**Comment by kou** [comment]
OK.
https://github.com/groonga/groonga/commit/3c2132fa2c253e7d0e81521be31c3d0905138a09 will use newer GNU Autootols.
The next Groonga release will support LoongArch.
