### ISSUE TITLE
ext/groonga/rb-grn-table.c内のドキュメントを英語にする

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#52]
See also: #33 ドキュメントを英語にする

これ:
https://github.com/ranguba/rroonga/blob/master/ext/groonga/rb-grn-table.c

一気にやるのは大変なので、関数ごとにひとつずつやるのがよさそう。

**Comment by komainu8** [comment]
将来的に GObject Introspectionに対応してドキュメントはGroongaの方から生成したので、この作業はこれ以上進めずにCloseする。
