### ISSUE TITLE
Groonga::Table#groupの:calc_targetオプションにGroongaのオブジェクトを渡せるようにする

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#53]
* https://github.com/ranguba/rroonga/blob/master/ext/groonga/rb-grn-table.c#L1443
* http://ranguba.org/rroonga/ja/Groonga/Table.html#group-instance_method
* 今は文字列かシンボルしか渡せない
* グループ化のキーはオブジェクトを渡せる

**Comment by kou** [comment]
オブジェクトを渡してうれしいケースがそんなにない気がしてきたので今のままでよしとする。
