### ISSUE TITLE
TokenRegexpで前方一致検索

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#62]
目的: 以下のように前方一致検索できる。

selected_items = items.select do |record|
  record.title =~ /\ARuby/
end

"Ruby"から始まるレコード（"Ruby Reference Manual"など）がヒットすること。

**Comment by myokoym** [comment]
親 #61

**Comment by myokoym** [comment]
終了条件: 以下のissueが完了すること。

* [ ] Groongaの正規表現APIの調査 #63
* [ ] Table#selectでGroongaのAPIを呼んでいる行をリストアップ #64
* [ ] Groongaの正規表現APIをRroongaにバインド #65
* [ ] Table#selectで文字列で前方一致のメタ文字（\A）を実装 #66
* [ ] Table#selectでRegexp型を受け入れ #67
* [ ] Table#selectでRegexp型で前方一致のメタ文字（\A）を実装 #70

**Comment by myokoym** [comment]
対応完了しました。私の今週のRroongaの作業はここで一区切りとさせていただきます。

**Comment by kou** [comment]
はい、ありがとうございました。
