### ISSUE TITLE
Groongaの正規表現APIの調査   

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#63]
親 #62

目的: 以下の関数の使い方を知る
アウトプット: 引数と戻り値の型をリストアップする

  * [x] `grn_operator_exec_match()`
  * [x] `grn_operator_exec_prefix()`
  * [x] `grn_operator_exec_regexp()`

**Comment by myokoym** [comment]
## `grn_operator_exec_match()`

https://github.com/groonga/groonga/blob/master/lib/operator.c#L902

```c
grn_bool
grn_operator_exec_match(grn_ctx *ctx, grn_obj *target, grn_obj *sub_text)
{
  grn_bool matched;
  GRN_API_ENTER;
  matched = exec_text_operator_bulk_bulk(ctx, GRN_OP_MATCH, target, sub_text);
  GRN_API_RETURN(matched);
}
```

### パラメタ

* grn_ctx *ctx
  * その時点のコンテキスト
* grn_obj *target
  * 検索対象
* grn_obj *sub_text
  * 検索クエリ

### 戻り値

* grn_bool
  * マッチしたかどうか

**Comment by myokoym** [comment]
## `grn_operator_exec_prefix()`

https://github.com/groonga/groonga/blob/master/lib/operator.c#L911

```c
grn_bool
grn_operator_exec_prefix(grn_ctx *ctx, grn_obj *target, grn_obj *prefix)
{   
  grn_bool matched;
  GRN_API_ENTER;
  matched = exec_text_operator_bulk_bulk(ctx, GRN_OP_PREFIX, target, prefix);
  GRN_API_RETURN(matched);
}
```

### パラメタ

* grn_ctx *ctx
  * その時点のコンテキスト
* grn_obj *target
  * 検索対象
* grn_obj *sub_text
  * 検索クエリ

### 戻り値

* grn_bool
  * マッチしたかどうか

**Comment by myokoym** [comment]
## `grn_operator_exec_regexp()`

https://github.com/groonga/groonga/blob/master/lib/operator.c#L920

```c
grn_bool
grn_operator_exec_regexp(grn_ctx *ctx, grn_obj *target, grn_obj *pattern)
{
  grn_bool matched;
  GRN_API_ENTER;
  matched = exec_text_operator_bulk_bulk(ctx, GRN_OP_REGEXP, target, pattern);
  GRN_API_RETURN(matched);
}
```

### パラメタ

* grn_ctx *ctx
  * その時点のコンテキスト
* grn_obj *target
  * 検索対象
* grn_obj *pattern
  * 検索クエリ（正規表現パターン）

### 戻り値

* grn_bool
  * マッチしたかどうか

**Comment by kou** [comment]
正規表現のサポートという観点ではこれらのAPIは使いません！

**Comment by kou** [comment]
正規表現のサポートとは別にこれらはGroonga 5.0.1の新機能なのでRroongaがサポートする必要があるAPIではあります。

**Comment by myokoym** [comment]
わかりました。では、正規表現サポートとは別のissueとして立て直します。

**Comment by kou** [comment]
それはいいことだと思います！

**Comment by myokoym** [comment]
立て直したので閉じます。

#80 #81 #82
