### ISSUE TITLE
TokenRegexpで後方一致検索

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#68]
#60

目的: 以下のように後方一致検索できる。

```
selected_items = items.select do |record|
  record.title =~ /Ruby\z/
end
```

"Ruby"で終わるレコード（"Perfect Ruby"など）がヒットすること。

**Comment by myokoym** [comment]
終了条件: 以下のissueが完了すること。

* [ ] TokenRegexpで前方一致検索 #62 
* [ ] Table#selectで文字列で後方一致のメタ文字（\z）を実装 #69
* [ ] Table#selectでRegexp型で後方一致のメタ文字（\z）を実装 #71

**Comment by kenhys** [comment]
#62は別の話では?

**Comment by myokoym** [comment]
#62 でAPIの調査やRegexp型の受け入れをやっているので、#68にとりかかる前にやる必要があります。

**Comment by kenhys** [comment]
そのとおりでした。
