### ISSUE TITLE
Segmentation fault occurs with sinatra

### ISSUE THREAD

**Issue by yk-twww** [ranguba/rroonga#94]
下のようなSinatraアプリケーションを実行し、"http://localhost:4567/"にGETアクセスするとsegvが発生する。
```Ruby
# -*- coding: utf-8 -*-

require "sinatra"
require "groonga"


Groonga::Context.default_options = {:encoding => :utf8}
Groonga::Database.create(:path => File.expand_path("../news.db", __FILE__))

Groonga::Schema.create_table("Entries", :type => :hash)
Groonga::Schema.change_table("Entries") do |table|
  table.text("content")
end

Entries = Groonga["Entries"]


get "/" do
  entries = Entries.select {|record| record.content =~ "hoge" }
  "foo"
end
```

環境
OS(CentOS 6.6)
ruby(2.1.2p95)
sinatra(1.4.5)
rronnga(5.0.0)

**Comment by kou** [comment]
まとめてもらってありがとうございます！

実行するときは`ruby app.rb`のように実行していますよね？
これで動かないのはSinatraがsinatra/main.rbで`at_exit`を使っているのが原因です。Rroongaも`at_exit`を使って終了処理をしているのですが、Rroongaの`at_exit`が先に走ってから（Rroongaの終了処理が終わってから）、Sinatraのアプリケーションが動き出してしまいます。

この問題の回避方法は次の通りです。

1. `require "sinatra"`ではなく、`require "sinatra/base"`を使って普通のRackアプリケーションの形にする。（`sinatra/base`では`at_exit`は使わない。起動するときは`rackup`などを使う。）
2. `require "sinatra"`は使うが、最後に明示的に`run Sinatra::Application`を書いて普通のRackアプリケーションの形にする。（起動するときは`rackup`などを使う。）
3. `require "sinatra"`の前に`require "groonga"`を持ってくる。（最初にRroongaを読み込むと、Sinatraの`at_exit`の方が最初に呼び出されるのでSinatraのアプリケーションが動いている間はRroongaの終了処理が動かない。）

**Comment by kou** [comment]
起動した後のことを少し補足します。

`Groonga::Context`オブジェクトはスレッドセーフではありません。マルチスレッドで動かすときはスレッドごとに`Groonga::Context`オブジェクトを作る必要があります。RackサーバーとしてPumaやThinやWEBrickを使うときはマルチスレッドになるので注意してください。

具体的にどう注意すればよいかというと。。。マルチスレッドで動かすときは`Groonga["テーブル名"]`の代わりに`context = Groonga::Context.new; context.use(database); context["テーブル名"]`とする必要があります。実は、`Groonga["テーブル名"]`は`Groonga::Context.default["テーブル名"]`のショートカットです。

というのは面倒だと思うのでマルチスレッドで動かさない方がよいと思います。

**Comment by yk-twww** [comment]
実行方法の情報が抜けてましたね。すみません。
(`ruby app.rb`で実行しています。)
丁寧なご対応ありがとうございます。
