### ISSUE TITLE
grn_table_create()がNULLを返したときのチェックを追加する

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#97]
`rb_grn_table_get_columns()`で`grn_table_create()`がNULLを返したときに、
現在はチェックしていないので後続処理で別のエラーになってしまう。

https://github.com/ranguba/rroonga/blob/master/ext/groonga/rb-grn-table.c#L612

対応内容:

* [ ] NULLが返ってきたときに、その時点で例外を投げるようにする
* [ ] 例外を投げる前にこのレイヤーで確保したメモリを解放する

**Comment by kou** [comment]
追加した。
